version: '3.8'

networks:
  jenkins_network:
    external: true

services:
  jenkins:
    image: vlad1kavkaz/jenkins-w-mvn
    container_name: jenkins
    networks:
      - jenkins_network
    ports:
      - "8082:8082"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_OPTS: --httpPort=8082
    depends_on:
      - nexus

  nexus:
    image: sonatype/nexus3
    restart: always
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - jenkins_network

volumes:
  jenkins_home:
  nexus-data:
